### PR TITLE
Small fix & documentation to get Instagram export working

### LINKED ISSUE #285: Migrate Instagram

### PR DESCRIPTION
**Pull request by rtannenbaum**
Small fix & documentation to get Instagram export working in the demo server.

Successfully exported photos from Instagram to Google.

Fixes #285

### CODE REVIEW

File: extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java [hunk 1]
```diff
@@ -31,6 +31,7 @@
   @Override
   public ImportResult importItem(UUID jobId, TokensAndUrlAuthData authData,
       PhotosContainerResource data) {
-    return null; // TODO: implement
+    // TODO(#337): Import is not supported for Instagram since their API does not support upload
```
Comment (seehamrun) [inline extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java]: tagging #337  explicitly so it ties the PR to the issue

Comment (seehamrun) [reply extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java]: Can we just delete the importer and throw an error in the TransferServiceExtension?

File: extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoExporter.java [hunk 2]
```diff
@@ -66,7 +63,7 @@ public InstagramPhotoExporter(ObjectMapper objectMapper, HttpTransport httpTrans
   @Override
   public ExportResult<PhotosContainerResource> export(UUID jobId, TokensAndUrlAuthData authData,
       ExportInformation exportInformation) {
-    return exportPhotos(authData, Optional.of(exportInformation.getPaginationData()));
+    return exportPhotos(authData, Optional.ofNullable(exportInformation.getPaginationData()));
```
Comment (holachuy) [inline extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoExporter.java]: Good catch! We should check the other Exporters when you get a chance.

File: extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java (hunk 1 above)
Comment (rtannenbaum) [reply extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java]: If you don't mind, I'll leave this up to the implementation of #337 - I think we'll probably end up doing it the way you described but in case we end up doing something else.

File: extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoExporter.java (hunk 2 above)
Comment (rtannenbaum) [reply extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoExporter.java]: Thanks! It threw a NPE when testing. I'll do a pass through for the others.

File: extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java (hunk 1 above)
Comment (seehamrun) [reply extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java]: sgtm!
