### PR TITLE
fixing forbidden characters for onedrive imports

### LINKED ISSUE #818: Microsoft OneDrive API throws 400 on import when file names contain forbidden characters
https://www.google.com/url?q=https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa%23invalidcharacters&sa=D

OneDrive API throws 400 when importing files with certain characters in their names. Characters are listed in this link.

### PR DESCRIPTION
**Pull request by pablomd314**
fixes #818

### CODE REVIEW

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java [hunk 1]
```diff
@@ -237,7 +242,7 @@ private String importSinglePhoto(
   }
 
   // Replace any non-whitespace, non-letter, or non-digit characters with -
-  static String cleanName(String name) {
+  static String cleanAlbumName(String name) {
```
Comment (seehamrun) [inline extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: Are the restrictions different for album and photo names? Can we use the same function for both? I wrote this version up as a quick fix for the albums but its not behavior that we rely on.

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java [hunk 2]
```diff
@@ -60,6 +62,8 @@
  */
 public class MicrosoftPhotosImporter implements Importer<TokensAndUrlAuthData, PhotosContainerResource> {
 
+  private static final List<String> FORBIDDEN_CHARACTERS = Arrays.asList("~\"#%&*:<>?/\\{|}.");
```
Comment (seehamrun) [inline extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: I'm a little confused why this has to be a list of strings instead of a list of chars - can you change it to either be 1 string (and get rid of the list) or a list of chars? 


Also can you add a comment pointing to the docs?

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java (hunk 1 above)
Comment (pablomd314) [reply extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: I assumed there was some reason for the cleanName, we can use the same though.

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java [hunk 3]
```diff
@@ -246,6 +251,16 @@ static String cleanName(String name) {
         .collect(Collectors.joining(""));
   }
 
+  // Replace forbidden OneDrive file/directory characters with -
+  static String cleanOneDriveName(String name) {
```
Comment (cnnorris) [inline extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: Yeah could you actually incorporate this logic into the transmogrification stuff I linked in the other comment? And make all the bits parameterizable, e.g.:
```
PhotoModel.cleanName(String forbiddenCharacters, String replaceWith, Int charLimit)
```

If you want to make an actual configuration object with defaults, etc. instead of using function params, that would also be cool.

Comment (pablomd314) [reply extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: I added a TransmogrificationConfig class that can be used for all data types in the future, with noop defaults. Idea being each importer can extend it, define the fields, and thus use their own Transmogrification class.

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java (hunk 2 above)
Comment (pablomd314) [reply extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: Changed to string, i meant to make it a list of chars initially, but string is easier to read i feel.

Added the doc in the MicrosoftTransmogrificationConfig

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftTransmogrificationConfig.java [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+
+// This class defines transmogrification paramaters for Microsoft imports
+public class MicrosoftTransmogrificationConfig extends TransmogrificationConfig {
+	/** 
+	OneDrive has forbidden characters for file names:
+		https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters
+	*/	
+	private final String 	PHOTO_TITLE_FORBIDDEN_CHARACTERS 	= "~\"#%&*:<>?/\\{|}.";
+	private final String 	ALBUM_NAME_FORBIDDEN_CHARACTERS 	= "~\"#%&*:<>?/\\{|}.";
+}
```
Comment (seehamrun) [inline extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftTransmogrificationConfig.java]: nit: new line at end of file

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java [hunk 5]
```diff
@@ -105,6 +107,10 @@ public ImportResult importItem(
       throws Exception {
     // Ensure credential is populated
     getOrCreateCredential(authData);
+    MicrosoftTransmogrificationConfig config = new MicrosoftTransmogrificationConfig();
```
Comment (seehamrun) [inline extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: Can this be a member var so its not initialized over and over again?

File: extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+import org.datatransferproject.types.common.models.TransmogrificationConfig;
+
+// This class defines transmogrification paramaters for SmugMug imports
+public class SmugMugTransmogrificationConfig extends TransmogrificationConfig {
+	// Smugmug doesn't allow photos to exist outside of a folder
+	private final boolean 	ALBUM_ALLOW_ROOT_PHOTOS				= false;
+	// Album size specified here:
+  	// https://github.com/google/data-transfer-project/pull/805/files
+	private final int       ALBUM_MAX_SIZE						= 5000;
+}
```
Comment (seehamrun) [inline extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java]: nit: new line at EOF

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java (hunk 3 above)
Comment (cnnorris) [reply extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: Awesome, thanks

File: extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java [hunk 7]
```diff
@@ -0,0 +1,12 @@
...
+
+import org.datatransferproject.types.common.models.TransmogrificationConfig;
+
+// This class defines transmogrification paramaters for SmugMug imports
+public class SmugMugTransmogrificationConfig extends TransmogrificationConfig {
+	// Smugmug doesn't allow photos to exist outside of a folder
+	private final boolean 	ALBUM_ALLOW_ROOT_PHOTOS				= false;
+	// Album size specified here:
+  	// https://github.com/google/data-transfer-project/pull/805/files
+	private final int       ALBUM_MAX_SIZE						= 5000;
```
Comment (cnnorris) [inline extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java]: What's up with this formatting

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java [hunk 8]
```diff
@@ -105,6 +107,10 @@ public ImportResult importItem(
...
+    resource.transmogrifyPhotos(config);
+    resource.transmogrifyAlbums(config);
```
Comment (cnnorris) [inline extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: I might consider combining these two together in the transmogrification interface, but I'll defer to you on that

File: portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java [hunk 9]
```diff
@@ -161,4 +161,27 @@ void ensureRootAlbum(boolean allowRootPhotos){
       this.albums = albums_;
     }
   }
+
+  // Replaces forbidden characters and makes sure that the name is not too long
+  void ensureCleanAlbumNames(String forbiddenTitleCharacters, char replacementCharacter, int maxTitleLength) {
```
Comment (cnnorris) [inline portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java]: Can you add tests for these new behaviors: https://github.com/google/data-transfer-project/blob/master/portability-types-common/src/test/java/org/datatransferproject/types/common/models/photos/PhotosContainerResourceTest.java

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java (hunk 8 above)
Comment (pablomd314) [reply extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: good idea, i'll put in a resource.transmogrify()

File: extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java (hunk 7 above)
Comment (pablomd314) [reply extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java]: thought it looked cool to have all the var names aligned

File: extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java (hunk 8 above)
Comment (pablomd314) [reply extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java]: we should move it over to ContainerResource at some point

File: extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java (hunk 7 above)
Comment (cnnorris) [reply extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java]: Oh it must have been displaying weird on my laptop

**Comment by seehamrun** [comment]
LGTM if you could run the google-java-formater on the files though that would be great -
